### ISSUE TITLE
Can't compile project

### ISSUE THREAD

**Issue by reussssya** [danielbanar/RustPlus#1]
Getting error when I add rustplus.pb.h:
`[build] C:\Users\reussssya\Desktop\qt5\rustapi\rustplus.pb.h(17,1): fatal  error C1189: #error:  This file was generated by an older version of protoc which is [C:\Users\reussssya\Desktop\qt5\rustapi\build\rustplus.vcxproj]`

I am using protoc version 3.17.0, whats wrong ?

**Comment by danielbanar** [comment]
use protoc-3.17.3-win32
